name: Android CI/CD
on:

  pull_request:
    branches: [ master ]
    
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./scripts/checksum.sh checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Check spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release
        run: ./gradlew assembleRelease --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace
      
