name: Android CI/CD
on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  unitTest:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Check spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release
        run: ./gradlew assembleRelease --stacktrace

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - name: Check reports
        run: |
          ls app/build/reports

  androidTest:
    needs: unitTest
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [ 23, 26, 30 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: true
          disk-size: 1500M
          heap-size: 512M
          script: ./gradlew connectedAndroidTest -x :benchmark:connectedBenchmarkAndroidTest